### ISSUE TITLE
Audio End Event?

### ISSUE THREAD

**Issue by JesterXL** [bp74/StageXL#124]
Hey chief, looking for an audio end event. I see an "on", but it has a signature I'm not familiar with. Anyway, just want a "end" event, assuming there is a Stream somewhere in here I can latch onto. I'll keep digging and hack it in if need be.

Thanks for the hard work!

**Comment by avstudios** [comment]
Hi Bernhard,
I've created a few games some time ago. That time I used stagexl 0.9.4 version. Everything worked fine until I updated Chrome browser to the latest version (42.0.2311.90). All loop sounds stopped working.
You " delayCall" workaround  to play sound again might work but I just wondering if there is any simpler solution. Anything changed since you looked it last time?
Thanks for any help in advance.

**Comment by bp74** [comment]
Hi,

There is a bug in Chrome 42, you can follow the issue here:
https://code.google.com/p/chromium/issues/detail?id=457099

Sebastien also reported this issue on the StageXL forum:
http://www.stagexl.org/forum.html?place=topic%2Fstagexl%2Fk3LQQ-7B4sQ%2Fdiscussion

I think it is a good idea to open a new issue for this problem:
https://github.com/bp74/StageXL/issues/189

The workaround Sabastien explained in the forum post may be a quick solution. I haven't tried it out myself so i don't know what the consequences may be. Since you've posted your question "Audio Event End" issue - there is good news for the next version of StageXL (you can also try it with the master branch of StageXL). The SoundChannel got an onComplete event and you can pause/resume SoundChannels too.

**Comment by avstudios** [comment]
Hi Bernhard,
Thanks for the links. I've updated stagexl lib as Sebastien suggested and it's in Chrome now.
I have not posted this issue but It's very good news about onComplete event and pause/resume sound. I will use it for sure in new game.
