### ISSUE TITLE
Support for loading different graphics for different screen sizes

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#184]
Hi,
Any sample code or reference for loading graphics for different screen sizes (HD, normal and low resolution graphics).

Thanks

**Comment by bp74** [comment]
Hi,

Yes there is support for low (normal) resolution BitmapDatas and hi resolution BitmapDatas. The feature is pretty simple right now but feedback is welcome so we can improve it. You use it like this:

    var resourceManager = new ResourceManager();
    resourceManager.addBitmapData("test", "images/test@1.png");

If the code runs on a HiDpi display (you can disable this by setting Stage.autoHiDpi = false) it will automatically load the image "images/test@2.png" instead of the "images/test@1.png". Of course you have to provide both images.

One thing we should add it support for "images/test@3.png" because some displays already have a 3x resolution compared to older phones. This isn't supported right now but it should be simple to add it.

**Comment by bp74** [comment]
Sorry, i made a mistake in my answer.

Actually the images need need to be named like this:

    images/test@1x.png
    images/test@2x.png

**Comment by bp74** [comment]
I just committed a change list which adds a better configuration of the HiDpi images that are loaded. It would be great if you could give it a try. I think i also found a bug in the previous implementation, but i don't have a device at hand to test it. So it is experimental :)

Take a look at BitmapDataLoadOptions.maxPixelRatio. The value defaults to 2, but you can set it to 3 if you provide images like this:

    /// 1x resolution files are named "{imageName}@1x.png"
    /// 2x resoultion files are named "{imageName}@2x.png"
    /// 3x resoultion files are named "{imageName}@3x.png"

    var resourceManager = new ResourceManager();
    resourceManager.addBitmapData("test", "images/test@1x.png");

**Comment by bp74** [comment]
Note to self: Take a look at the Stage.autoHiDpi, maybe we should change this to maxPixelRatio too.

**Comment by bp74** [comment]
Fixed in StageXL 0.12
