### ISSUE TITLE
Color Transformation changes color of all instances

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#187]
I am trying to change the color of Bitmap using color transformation but when I apply the change to one bitmap, color of all other instance also gets changed. How can I apply the change to single instance.

**Comment by bp74** [comment]
Of course it does. You actually don't apply the color transformation to the Bitmap instance. Take a closer look and you will see that you apply the color transformation to the BitmapData instance. The BitmapData is shared between all Bitmap instances.

You have two options: Create a clone of the BitmapData instance (there is a clone method on the BitmapData class) to get a second BitmapData. You could apply a color transformation to one of those BitmapDatas without affecting the other one.

It depends on your use case but the second option may be the better one. You can apply filters to every display object. You can do this:

    var bitmap1 = new Bitmap(myCoolBitmapData);
    var bitmap2 = new Bitmap(myCoolBitmapData);
    bitmap1.filters = [new ColorMatrixFilter.adjust(hue: 0.5)];
    bitmap2.filters = [new ColorMatrixFilter.adjust(hue: 0.3)];

There is another filter too, called TintFilter. It is not as powerful as the ColorMatrixFilter but it may be sufficient for your use case. The constructor of the ColorMatrixFilter shown above is just an example, there are many different other options to create a ColorMatrixFilter.

http://www.stagexl.org/docs/api/index.html#stagexl/stagexl-filters.ColorMatrixFilter

Hope this helps,
Bernhard

**Comment by bp74** [comment]
I should add: To use the second options with the filters, you have to use the WebGL render engine. The default is the Canvas2D engine, but filters need the WebGL engine.

**Comment by KakashiSensei** [comment]
Thanks, I got now. I will be using 1st method so that it can run on mobile browsers which might not support WebGL. Is there any performance difference between the two?

**Comment by bp74** [comment]
Yes there is a big difference. First you need twice as much memory because you create a clone of the BitmapData. The other difference is that WebGL can be 10x as fast as Canvas2D if you follow some simple rules. One of those rules is that you should use an TextureAtlas in WebGL. If you create a clone of a BitmapData you automatically create a new WebGL texture, which means you don't use a texture atlas which will hurt performance. 

You can learn more about it here:
http://www.stagexl.org/example/basic/texture_atlas/doc/readme.html
