### ISSUE TITLE
frameRate argument for Stage is not working?

### ISSUE THREAD

**Issue by EasonPai** [bp74/StageXL#190]
Hi Bernhard,

I want to make my app runs with lower fps like 30 instead of the default 60.
Then I tested with example benchmark/bunny_mark to changed frameRate property as
```
var stage = new Stage(canvas, webGL:true, color:Color.White, frameRate:1);
```
and run it again, I expected the fps should be different, but the the result fps is remain the same as 60.

Is this an issue or maybe I missed some configuration?
Thanks~

BR,
Eason

**Comment by bp74** [comment]
Hi Eason,

The frameRate configuration of the Stage is primarily for the "Toolkit for Dart" which uses the MovieClip class to play timeline animations created in Flash Professional. Since timeline animations need a target frameRatewe added this configuration to the Stage some time ago. In the next release this configuration will probably go away anyway.

In fact you can't configure the frame rate of the Stage, it will always render as fast as possible. If you want to take control over the frame rate, you could take a look at the Stage.renderMode property. Here you can configure if the Stage should refresh automatically, once or stop rendering. 

Hope this helps,
Bernhard

**Comment by bp74** [comment]
Maybe a better way to control the frame rate of the Stage is the RenderLoop class. It's pretty simple and you could change it's behavior to fit your needs - maybe skip a frame if the last one was just a few milliseconds ago.

**Comment by EasonPai** [comment]
Dear Bernhard,

Got it, I will give it a try to control it over RenderLoop, Thanks a lot! 
(sorry for the late reply to your super efficient answer, we have a local holiday these days)

BR,
Eason

**Comment by bp74** [comment]
I'm happy to help, if it does not work as accepted please reply to this issue and i will reopen it. Btw. the master branch on GitHub already removed the frameRate parameter on the Stage constructor. Thanks for making me aware of this strange leftover from the past :)
