### ISSUE TITLE
HtmlObject is too big and blurred in retina

### ISSUE THREAD

**Issue by kasperpeulen** [bp74/StageXL#206]
I tried playing with the HtmlObject class, but there is seem to be some scaling issue, probably because I have a retina screen.

![image](https://cloud.githubusercontent.com/assets/1035299/8509748/33fc1a40-22b7-11e5-9da0-3156ca1e5085.png)

this is how a ButtonElement looks like for example

**Comment by bp74** [comment]
Okay i see ... i haven't had the time to test it, but i think this is the problem: The HtmlObject uses the same transformation matrix as all the other display objects in StageXL. Since we have to scale all the other display objects by a factor of 2x or 3x depending on the HiDpi screen of the device, we also scale the HtmlObject by this factor - which is wrong. The scaling by the "pixel ratio" of the HiDpi screen needs to be undone for HtmlObjects.

**Comment by bp74** [comment]
There is a fix on the master branch. You have to update your pubspec.yaml file to change the StageXL reference from Pub to this git repository. You can do this by adding this to your pubspec.yaml:

    dependency_overrides:
      stagexl:
        git: https://github.com/bp74/StageXL.git

You only have to use the "dependency_overrides" if you use other StageXL extension libraries. If you just use StageXL, you can set the git path reference also in the normal "dependencies".

**Comment by kasperpeulen** [comment]
Nice, thanks, works for me :)

**Comment by kasperpeulen** [comment]
That looks better:
<img src="http://i.imgur.com/xXv78xd.gif" width="224" height="206">

**Comment by bp74** [comment]
Happy to see that it works now. Sorry for this issue.
I think i will release a 0.12.0+1 version later today.

**Comment by bp74** [comment]
Fix released with version 0.12.0+1
