### ISSUE TITLE
WebGL line drawing doesn't work

### ISSUE THREAD

**Issue by mnordine** [bp74/StageXL#220]
Lines do not render using graphics API when renderEngine is WebGL:

https://gist.github.com/mnordine/fed71fb36799d337473c

It works fine if renderEngine is Canvas2D.

**Comment by bp74** [comment]
Yes that's a known issue. The vector graphics capabilities of the WebGL renderer are very limited. We add features on every release of StageXL but it's a difficult task because the WebGL APIs are not designed to support vector graphics. Currently only solid fills are supported, the next release of StageXL probably will add lines. 

It never was a top priority to add full support for graphics in WebGL because graphics are hardly used in a game or other applications. Most users need support for textures, texture atlases, filters, etc but drawing lines is not so important. That said, recently the requests for better support of graphics in WebGL got more and therefore the last version of StageXL started to support the most basic features (drawing paths and doing solid fills) for graphics.

**Comment by bp74** [comment]
This feature was released with version 0.13.1
Graphics support for WebGL is still not complete, but we get closer :)
Still missing: Gradient and Pattern fills and strokes, and some minor features.
