### ISSUE TITLE
Rectangle constructor should set params to zero by default

### ISSUE THREAD

**Issue by mnordine** [bp74/StageXL#234]
AS3 does this as well: http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/geom/Rectangle.html#Rectangle()

**Comment by mnordine** [comment]
Sorry, this is more trouble than it's worth because of generics.

**Comment by bp74** [comment]
Hi, yes this would be a good idea but as you said it's a problem with generics. In other languages like C# you could do something like this: `T x = default(T)` which gives you a 0 in case of int and 0.0 in case of double. Unfortunately this concept does not work in Dart because the default value of all types is `null`. But thanks for bringing up this suggestion!

**Comment by mnordine** [comment]
> In other languages like C# you could do something like this: T x = default(T)

Very interesting, did not know.

Actually, at first glance, because Rectangle's generic type inherits from `num`, I thought you could just do:

```dart
T left   = 0;
T top    = 0;
T width  = 0;
T height = 0;
```

but, apparently not
