### ISSUE TITLE
Missing TextField.setTextFormat()

### ISSUE THREAD

**Issue by mnordine** [bp74/StageXL#249]
Flash has  the ability to set a different `TextFormat` for a given range of characters: http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/TextField.html#setTextFormat()

It'd be a very nice feature to have this ability in StageXL as well.

**Comment by bp74** [comment]
Thanks for the suggestion. 
Have you tried to use https://github.com/bp74/StageXL_RichTextField ?
It should give you similar features.

**Comment by bp74** [comment]
You can try it here: http://www.stagexl.org/show/richtextfield/sandbox/example.html

**Comment by mnordine** [comment]
That works, but why doesn't `TextField` have those capabilities?

**Comment by bp74** [comment]
Because there are many ways to implement a feature like this and it's probably a good idea to create an extension library for it. It's easier to deprecate an extension library than remove features from StageXL. For example Flump seemed to be a nice export format for Flash developers, nowadays it's much better to use GAF. So it was a good choice to create StageXL_Flump instead of adding Flump support to StageXL. I only want to add things to StageXL if it is pretty sure that they will survive for a long time. For you as developer it doesn't make much of a difference anyway.

**Comment by mnordine** [comment]
> For you as developer it doesn't make much of a difference anyway.

My only objection to this is for devs coming from AS3, they would be quite puzzled by this missing feature. But at least this extension is listed in the README.
