### ISSUE TITLE
Possible idea

### ISSUE THREAD

**Issue by unicomp21** [bp74/StageXL#286]
Use https://www.npmjs.com/package/js_facade_gen to create dart wrapper for babylonjs, which can be used to extend StageXL.  StageXL is awesome as a 2D framework, Babylonjs is pretty good as a 3D framework.

**Comment by nilsdoehring** [comment]
Thank you, ideas are always welcome!

Actually, this has been done already: https://github.com/block-forest/babylonjs-dart-facade
StageXL integration works by rendering Babylon Canvas off stage and copying bitmaps into a DisplayObject. Not ideal, but no big performance hit, either. Mouse and Keyboard events work – no solution for Touch events yet, because Babylon expects these to happen on it's own Canvas and I haven't been able to find time to investigate a workaround.

Anyways, sample code should get you started rather quickly.

Please note:
- Readme.md is outdated
- Sample currently shows nothing because it tries to load resources from cdn.babylonjs.com, and they recently changed their Access-Control-Allow-Origin header recently :-/
