### ISSUE TITLE
Chrome v70+ disables Touch API on "Desktop Devices"

### ISSUE THREAD

**Issue by MurrayLS** [bp74/StageXL#321]
Chrome [released an update](https://www.chromestatus.com/feature/4764225348042752) that disables the touch API by default on Desktop devices.

This means that Chromebooks that have touchscreens are not able to use the touch functionality by default on the canvas.

According to discussion on the bug tracker for that feature, Edge has done a similar thing, although I don't have a touch device that can run Edge to confirm whether this affects devices such as Surfaces.

TouchEvents can still be added to the page, at which point they are effectively re-enabled as per the document above, however the method being used to check whether touch is supported in the display/stage.dart file, line 185, is returning false, so those events are not being added.

One solution would be to find an alternate feature detection method for Chrome (and possibly Edge), another would be to add support for PointerEvents per their document, and a third, dirty, solution would be to add a force-touch-events InputEventMode.

**Comment by AndrewLugg** [comment]
This issue has been resolved on Chromebooks and Surface devices, with the Dart 2.4 and above. But the update has broken touch listeners on iOS 9.3.5

There is a work around, you can modify lib/src/display/stage.dart, and on line 185, remove "env.isTouchEventSupported" so that all devices get the touch listeners. It isn't a great fix, but it means that old iOS devices will work.
