### ISSUE TITLE
Pause and Resume Sound

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#96]
Is there a way to pause and resume sound?

Sound Channel has only stop option....

**Comment by bp74** [comment]
It looks like that Google won't fix the "enden" event anytime soon. Therefore we have implemented a workaround to extend the current SoundChannel API. The new SoundChannel API looks like this:

    SoundChannel.onComplete;     // An event that fires as soon as the SoundChannel completed the playback.
    SoundChannel.loop;           // Getter if the SoundChannel is looping.
    SoundChannel.stopped;        // Getter if the SoundChannel is stopped.
    SoundChannel.position;       // Getter of the playback position in seconds.
    SoundChannel.sound;          // Getter of the parent Sound.
    SoundChannel.paused;         // Getter/Setter to pause the SoundChannel.
    SoundChannel.soundTransform; // Getter/Setter to set the sound transformation of the     SoundChannel.
    SoundChannel.stop();         // Stop the playback of the SoundChannel. Can't be resumed!
    SoundChannel.pause();        // Pause playback of the SoundChannel. 
    SoundChannel.resume();       // Resume playback of the SoundChannel.

Since nobody can trust the audio implementations in different browsers and on different devices, everything is experimental and much more testing is required. It would be great if everyone could help testing the new implementation on their devices.

**Comment by bp74** [comment]
Fixed in StageXL 0.12
